In [2]:
import sqlite3
import pandas as pd

con = sqlite3.connect("../data/raw/ipl.db")

def q(sql):
    return pd.read_sql(sql, con)

In [4]:
# command 1

q("SELECT COUNT(*) FROM matches;")

   COUNT(*)
0      1212

In [12]:
# Command 7 — COUNT and AS
q("""
SELECT COUNT(*) AS total_matches
FROM matches;
""")
# My observation:
# COUNT(*) counts the number of rows in the matches table.

   total_matches
0           1212

In [10]:
# Command 9 — GROUP BY
q("""
SELECT venue, COUNT(*) AS matches_hosted
FROM matches
GROUP BY venue
ORDER BY matches_hosted DESC;
""")
# My observation:
# GROUP BY creates one group for each venue and COUNT(*)
# counts the matches in each group.

                                                venue  matches_hosted
0                                        Eden Gardens              77
1                                    Wankhede Stadium              73
2                               M Chinnaswamy Stadium              65
3                                    Feroz Shah Kotla              60
4                            Wankhede Stadium, Mumbai              57
5           Rajiv Gandhi International Stadium, Uppal              49
6                     MA Chidambaram Stadium, Chepauk              48
7                              Sawai Mansingh Stadium              47
8                 Dubai International Cricket Stadium              46
9            MA Chidambaram Stadium, Chepauk, Chennai              38
10                   Narendra Modi Stadium, Ahmedabad              37
11         Punjab Cricket Association Stadium, Mohali              35
12                               Sheikh Zayed Stadium              29
13                            Sharjah Cricket Stadium              28
14                              Eden Gardens, Kolkata              27
15                        Arun Jaitley Stadium, Delhi              27
16  Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...              26
17                   M Chinnaswamy Stadium, Bengaluru              24
18  Rajiv Gandhi International Stadium, Uppal, Hyd...              23
19            Maharashtra Cricket Association Stadium              22
20                 Dr DY Patil Sports Academy, Mumbai              20
21                     Sawai Mansingh Stadium, Jaipur              19
22                         Dr DY Patil Sports Academy              17
23                          Brabourne Stadium, Mumbai              17
24                         Subrata Roy Sahara Stadium              16
25                 Rajiv Gandhi International Stadium              15
26                              M.Chinnaswamy Stadium              15
27                                          Kingsmead              15
28                               Arun Jaitley Stadium              14
29      Maharashtra Cricket Association Stadium, Pune              13
30  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...              13
31                                    SuperSport Park              12
32                       Sardar Patel Stadium, Motera              12
33  Punjab Cricket Association IS Bindra Stadium, ...              11
34             Saurashtra Cricket Association Stadium              10
35       Punjab Cricket Association IS Bindra Stadium              10
36  Maharaja Yadavindra Singh International Cricke...              10
37                                  Brabourne Stadium              10
38                             MA Chidambaram Stadium               9
39                             Holkar Cricket Stadium               9
40       Himachal Pradesh Cricket Association Stadium               9
41                   Zayed Cricket Stadium, Abu Dhabi               8
42                              New Wanderers Stadium               8
43                Barsapara Cricket Stadium, Guwahati               8
44                                   St George's Park               7
45                                           Newlands               7
46                 JSCA International Stadium Complex               7
47                                   Barabati Stadium               7
48   Shaheed Veer Narayan Singh International Stadium               6
49  Himachal Pradesh Cricket Association Stadium, ...               6
50  Punjab Cricket Association IS Bindra Stadium, ...               5
51                                      Nehru Stadium               5
52  Maharaja Yadavindra Singh International Cricke...               5
53                                         Green Park               4
54  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...               4
55       Vidarbha Cricket Association Stadium, Jamtha               3
56                              De Beers Diamond Oval               3
57                                       Buffalo Park               3
58                                    OUTsurance Oval               2